### ISSUE TITLE
SS-2: Add A Generative AI Tree

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem-website#9]
We are generating databases from our AI and it would be cool to make it like a tree and have links to the chemical ecosystem:

https://github.com/Global-Chem/Chemical-Ecosystem

Global-Chem
 -----Sex
 -----War
 -----Cannabis
          -----Sativa
         ------Indica

**Comment by LadyBluenotes** [comment]
@Sulstice 

Due to the length of the page already, I think we could add this into another page. If we add another component, such as this one, we risk the webpage being lengthy as well as losing the direction of the page (which is to chat about Global Chem as a whole).

My thoughts are to switch the button intended for #11 issue. #11 could be made into an info section (such as "Looking for our NFT Gallery? Click here!" type of thing) and then we can have this navigate you to another page where you can see a better representation for all the data sets here.

I think if we continue to add things to the web page, however, we're going to have to consider moving similar components to their own pages. Landing pages should be more about the org / introducing the org vs getting into nitty gritty details (that is usually reserved for other pages) and we're starting to bridge the category into being unclear.

Thoughts?

**Comment by Sulstice** [comment]
Yeah definitely. I think with the way you have built the website. Prior I was thinking it was just going to be a static site we occasionally change but with the way we have built stuff we can get a pretty effective platform going to extend our applications. How to add components and new applications is going to be tricky but I think worth it in the long term.

**Comment by Sulstice** [comment]
You will have to teach us I think.
